version: '3'

volumes:
  db:
  redis:
  cert_cache:
  soundboard:

networks:
  default:

services:
  app:
    build:
      context: ../
      dockerfile: yagpdb_docker/Dockerfile
    restart: unless-stopped
    command:
      - "/app/yagpdb"
      - "-all"
      - "-pa"
      - "-exthttps=false"
      - "-https=false"
      - "-feeds=reddit,twitter"
    depends_on:
      - redis
      - db
    networks:
      - default
    volumes:
      - cert_cache:/app/cert
      - soundboard:/app/soundboard
    ports:
      - '10.8.41.197:5000:80'
      #- '5001:443'
    env_file:
      - app.env

  redis:
    image: redis
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis:/data

  db:
    image: postgres:11
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - db.env

